### DISCUSSION TITLE
How to use the name and logo from the brand.yml file in a Shiny for R app?

### DISCUSSION THREAD

**Discussion by durraniu** [posit-dev/brand-yml#74] [Q&A] [answered]
Colour and typography are automatically applied, but how to use the name (meta) and logo specified in brand.yml in an R Shiny app?

**Comment by gadenbuie** [comment, marked as answer]
Hi @durraniu! We will eventually have a `brand.yml` package with its own `read_brand_yml()` function, but for now you can get a list with the `brand` data from the `brand` attribute of the theme returned by `bs_theme()`, e.g.

```r
theme <- bs_theme(brand = TRUE) # or just bs_theme()
brand <- attr(theme, "brand")
```

With `brand = TRUE`, you're signaling that there _must_ be a `_brand.yml` file in the project. By default `bs_theme()` will find and apply the `_brand.yml` file but won't error if one isn't found (in which case the `brand` attr is `NULL`).

Then you can read properties from the `brand` list, e.g. `brand$meta$name$full`.

**Reply by durraniu** [reply]
Thanks! That works for me.

**Reply by gadenbuie** [reply]
Oh, also to answer your question about `logo`: You should specify logo paths relative to the `_brand.yml` file, and then you can combine `brand$path` with the `brand$logo$...` values. When we have a `brand.yml` package in R, we'll handle those things for you, as well as a bunch of other validation steps for `brand$logo`. (`brand$path` is added when we read `brand` from a file.)

**Reply by durraniu** [reply]
Thanks for the details, appreciated.

**Comment by durraniu** [comment]
Thanks for your guidance so far @gadenbuie. I tried using the logo from `brand$logo` with a jpg file in `brand` folder, but the logo did not render. The `www` approach does work as expected. What mistake am I making? 
```
library(shiny)
library(bslib)

my_theme <- bslib::bs_theme(brand = TRUE)

# The www approach works---------------------
# addResourcePath("www", "www")
# img_path <- "www/bird_2.jpg"

# The brand approach does not work-------------------
brand <- attr(my_theme, "brand")
path_to_brand_yml <- brand$path
path_to_brand <- dirname(path_to_brand_yml)
img_path <- paste0(path_to_brand, "/", brand$logo)

# Footer----
app_footer <- tags$footer(
  style = "padding: 18px; bottom: 0; width: 100%;",
  tags$div(
    style = "float: left;",
    tags$span(
      tags$img(
        src = img_path,
        width = "150px",
        height = "auto",
        class = "me-3"
      )
    )
  ),
  tags$div(
    style = "float: right;",
    actionButton("faq", "FAQs")
  )
)


# Define UI for app that draws a histogram ----
ui <- page_navbar(
  theme = my_theme,

  footer = app_footer,

  # App title ----
  title = "Hello Shiny!",

  # Sidebar panel for inputs ----
  sidebar = sidebar(

    # Input: Slider for the number of bins ----
    sliderInput(
      inputId = "bins",
      label = "Number of bins:",
      min = 1,
      max = 50,
      value = 30
    )
  ),

  # Output: Histogram ----
  nav_panel(
    title = "Plot",
    plotOutput(outputId = "distPlot")
  )
)

# Define server logic required to draw a histogram ----
server <- function(input, output) {

  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  # This expression that generates a histogram is wrapped in a call
  # to renderPlot to indicate that:
  #
  # 1. It is "reactive" and therefore should be automatically
  #    re-executed when inputs (input$bins) change
  # 2. Its output type is a plot
  output$distPlot <- renderPlot({
    x <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)

    hist(
      x,
      breaks = bins,
      col = brand$color$primary,
      border = "white",
      xlab = "Waiting time to next eruption (in mins)",
      main = "Histogram of waiting times"
    )
  })
}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```

Note that the `brand` folder contains this `_brand.yml` file:
```
meta:
  name: brand.yml
  link: https://posit-dev.github.io/brand-yml

logo: bird_2.jpg

color:
  palette:
    black: "#1A1A1A"
    white: "#F9F9F9"
    orange: "#FF6F20"
    pink: "#FF3D7F"
  foreground: black
  background: white
  primary: orange
  danger: pink

typography:
  fonts:
    - family: Open Sans
      source: google
    - family: Rubik
      source: google
    - family: IBM Plex Mono
      source: google

  base: Open Sans
  headings:
    family: Rubik
    weight: 400
  monospace: IBM Plex Mono

```
