### ISSUE TITLE
Rename `template` to `defaults`

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/brand-yml#1]
And move Quarto-related defaults into a `quarto` key.

```yaml
defaults:
  quarto:
    format:
      html:
        background-color: home-depot-red
      revealjs:
        logo: fancy-logo-3
  shiny:
   navbar:
      logo: fancy-logo-2
      title: ACME Data Science
  bootstrap:
    enable-rounded: false
    link-decoration: none
```
