### ISSUE TITLE
Make it very easy to quickly set font-family

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/brand-yml#21]
As proposed by @cpsievert, we could make it very easy to set font families by letting `typography.{base,headings,monospace}` take a string that we'd map to the `family` property.

```yaml
typography:
  fonts:
    - family: Open Sans
      source: google
    - family: Roboto Slab
      source: google
    - family: Fira Code
      source: google
  base: Open Sans
  headings: Roboto Slab
  monospace: Fira Code
```

For someone who just wants to pick fonts quickly even this is still a bit of boilerplate. In pkgdown and rmarkdown, we've used a syntax like this to declare in-place Google fonts:

```yaml
typography:
  base: { google: Open Sans }
  headings: { google: Roboto Slab }
  monospace: { google: Fira Code }
```

Instead of this, I wonder, if we're comfortable making Google Fonts the default, we could automatically add Google Font declarations for font families that don't have a counterpart in `typography.fonts` and are a single font family name. 

With this approach, in the following example we'd use Roboto Slab and Fira Code from Google Fonts but rely on locally-installed Open Sans (i.e. opting out of Google Fonts).

```yaml
typography:
  fonts:
    - family: Open Sans
      source: file
  base: Open Sans
  headings: Roboto Slab
  monospace: Fira Code
```
