### ISSUE TITLE
Formalize location of Bootstrap variables and settings

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/brand-yml#32]
Currently, Quarto passes `color.palette` directly to Sass as Sass variables. This is certainly helpful; it means that users can do things like this

```yaml
color:
  palette:
    charcoal-black: "#1A1A1A"
    navbar-bg: charcoal-black
    enable-rounded: "false"
```

However, it's problematic for a few reasons:

1. I don't like the blending of concerns; this opens the door for `color.palette` to hold information that isn't about the actual color palette, which will be confusing to people using brand via the Python or R packages.

1. I anticipate some changes to behavior for `color` in the Python and R packages that will specifically assume these values are colors. The biggest is that we plan to turn values in `color.palette` into `$brand-{name}: {color}` Sass (and CSS variables). 

1. I can also see adding utilities that will make a strong assumption that these values point to colors, e.g. using libraries to manipulate colors in R or Python.
 
1. Finally, a smaller issue is that the type checking of `color.palette` requires values be strings, which means we need `enable-rounded: "false"` instead of `enable-rounded: false`.

I propose that we consolidate on a common place to pass variables to Bootstrap that can be picked up by both Shiny and Quarto: `default.bootstrap`. (This would also be useful for pkgdown, rmarkdown and more.) We'd reserve `default.bootstrap.version` to track required version (as a major version value, i.e. currently defaulting to 5). All other variables would be passed into the defaults layer.

The above example would become

```yaml
color:
  palette:
    charcoal-black: "#1A1A1A"

defaults:
  bootstrap:
    version: 5 # optional
    navbar-bg: $brand-charcoal-black
    enable-rounded: false
```

Notice that a general principle of `defaults` is that once you're adding settings there, you're clearly targeting a specific output. So we can directly use Sass variables rather than relying on the color substitution we do in `color` and `typography`. Having a consistent pattern for accessing the brand color palette means `defaults.bootstrap.navbar-bg` can directly use `$brand-charcoal-black`.

**Comment by gadenbuie** [comment]
We talked about this internally, but `defaults.bootstrap` being only variables seems like it will end up being too constraining. In Shiny implemented `defaults.shiny.theme.{functions,defaults,mixins,rules}`, and I think we should do something similar for `defaults.bootstrap`.

E.g. instead of

```yaml
defaults:
  bootstrap:
    enable-rounded: false
    link-decoration: none
``

this would work

```yaml
defaults:
  bootstrap:
    defaults:
      enable-rounded: false
      link-decoration: none
    rules: |
      h2 { color: pink }
```
