### ISSUE TITLE
NHS brand

### ISSUE THREAD

**Issue by send2dan** [posit-dev/brand-yml#53]
For the UK it would be helpful to publish branding for the National Health Service (NHS) - The UK's largest employer after all

**Comment by gadenbuie** [comment]
Great idea, thanks! I started working on this a bit, here's what I came up with. You can see it in action in this [shinylive app](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGA+gIwE5QgEwHQCeMANmADRgDGA9hAC5z1Jjx1SIA6EABN9PIm5devAM4ALahjqCAcgAkAysJEAzAK7FicqHQCWtKMW7y4RuuO6K4GAG57KcFcT0QA1px4jJA7uLp0AA6iiAD0oQDuUXgQ4qJ46m4qvJjYOIL+QSHhURF4jADmxGkxcQluobGiejiM+nQEoTV1eg0AtAXqzS4QcKKhXFwAxNwjACLUERDE1FA43BZw3AqK3DMF1KLcadyidFJLizB8cAAedAvU3OhYuIQkw6PcAJrU6gDkWn5QtodX6oEcLpDuI9FtRHBKPpaNwIq1LItuDQMBhIRdVHpiEt+H1HutqJ4Rrw9DAoAU+oSRLxxGZahhBFU2vi8KJbAVHlSaXMbG0IqCGAy4kzqBtefy4Cy2RzdqStILRMLRQ5aJL2RAidx4Dg9OoYBlaTZpcUMOT9dyMIMIDQZvSVIEjHAAnBPFSRgBhA4ndR0LDELYACgAMnBfsYAEwASmSsPFgg4YCGADFkyn49G0MVKB4hAmwwBmACMibDAAY015eAVUQQ2kCMNn40MACxhgCsrYAbHny1Sq3AazAanGEwB2DsADg7AE4wz2RH2a-ascOhgBRcersar1dz3jRkYAIWI6j63CDIbgxgLUYr3AzJ9rUHrK5LJbzJfHI93d+PzpzQ1fVtVwPcdv3vOA2kwPQCn8F8SxHMM3R3MB01-JloNg-8mwLA8O1XDswLQqAAEd1HYf9XwAQSnJDv33bgAHFUUYANg1Dbg8xvXtmIgR9nwoksOxHJsvxQ28+0YOCpy7Kdvwk3iXBgmR-xHccD1XUs5J4toSLIuDKKbKdZLEql6IABXUDBAixLYdjM1w3FEaNAks6y-0bPN33g2cTJEQIHL4htRzdMNx3bb9-PcFdKI01sR27Xy91vEYACU4BwJzb1RHBApXcdKILVs81AxLuGylcxkosMpwLN1414EZV3gE1GEoAgrBsexHC2NKcGjejnkvGYIls3BuAAeVucloykbBTX-Tc1Nfb8CCGyZeSfPV-2TEDapWtaIhXRMYoLZbStWrR1rgZryStAgjsTfCzoa7gUsowNuFOgsOysTRAnESyXgO-rku4A9qGoOg9iwQIkWoG1thcKAIS2NpuHUaoIAKJEZhRi5SToSgaS2OELDeC4cABFxKF0AwIGjVxtQ2QRwMC6M2uwFmiNIqBowYIxBHknSeZBl7rFJegHDhhHkeqAoIHgehMt4VQDirN5cC5qAsxUNBtbcdX1E1mNWicLxAgwEkn3un8TxUCEaFwa3BerNmvAYaQ9Gd7gFzaJczbEdRKG6kIfZ4lQgSxmxBGylQIifCBXAKQQLuGjaMBgFRXFVrmH0U-xnAw5Tff9iOn2zX26ySen6AIQIRRh8R7pUVWlZdEQRlkSG-0TDBvWgmxuDBbY1gcFj0u4VuLgIN53nmcQfj+bgXIwInkaWKRuBwSZplmPrQbR1RYExG3e-78kMG4AB1EsC3osQ3lXv8MSxe-J8xCkhFBqk0ftCxBCnv0M++gL6BgACo3wLG0dsKVqASzwAEVQb9eC-10OIABtAoahGAQPDA4DIFtA7K2cGxB8CIOQSICIcAi4s3hvvKkDCv4-0nsfYgNtKKWyMNGB+llHCCFEAQPY10VC63Xu3FWrCbbxg4V7YgZBdjYAVBCS2SDSpUJodwJsy1bzVAAF5-m+oEU40YegQRpBogseBWyWmpLSJOIRoxH0HGw4cMijDyNEIotoyi9CqOjOopSggRzaKpKYto5jAmfTwG2dm8MpC5zNlwWoR9NBQ3bmgCGUMfRQECOIrecAUnEDSdwp4KxdiBEhL4qWtgnxewzKeGgmh5hoCWHMWo88bABwYYwKA9S2gYA1u0gBRgIRgAAL5kHADiZgKBrRSHiKISgohRDkCoJguozBwh+ACMEMIoQCjwnUGgPANAYChDoBENA-QMmQ2hjk0IGZqBoFCLYVseA8zvNCNUBgoRZaOn6Is5ZoRZlxIwAspZmUuB4DQDlVmp0SzcBANLeJyKMBtEdtkvY-oAAkcLXwRgANx3n1obXA6LQWCFxWheFRKxlQphZBNCpYEVIrmfSVF5L6BYCxVSh8zLCXEqzKSnKbLKWs2ZbS+lsK0JeURaiwQbLOWYroDi1mXkBV6yFQMo2IqKXcF5RBLykqIDQulQ+LRLL5UcoxdylVBq2gWo1SS7VZLRX6tZha41prGUPlbK+OVbrFU2uRna1mfqSxOq1YM8lNoxVoXDV6hlrMOz+tZXqoNmDbWqrQimiNRLNUGxdbq2N7qc2vkTWaiCwTLWBtBUqrN9rq2RsLdGt1jby3cDpSapNaFxypqtRmrlIbs0Pj7XmwVLadUxpRfasdFafUQSnP22tNp63DvtUu8dBbhXTvZRujtXapVtEZtBagbR4UBvTXW4NPKT2inhc2ndba71nppZ2o9L62jMsvSWwdyqcWfv5fm51ra9XYsAwej9uBT1tFlWm3917M3rs-eq4DUap3Pug6KI177u05U-Ran9KK-0NoI-itDk7XVgbIyWedn7w1EfZSR5DWGz3hsfUW3dlL6OQbw8e1jhDl1XtXTeu1n7c0cdAyW8DAnc10YE9WxjCrENDtvQp8jE6n3UfU7R3D3rP1jqU9apDammZnrHZJjD2mzNtDnXphln7N1GeY6ZmDm7LNUek453jR6V5uXPUJhDImTN2r81iALW6QNWek2FiCb6u3eti1+wLxGVP-uxUloDmnONtsy7xxLrlwtwYHWlhtSXUPZakzO8r+WGVJcI-B1LwXVOhcKxBR1FGtMxbaw62rOUksMca0x0r66Bsae3TlsDY3dMJbqz13NzmRs8qSxJzrk3utWXC3J+z-WeuKaG8p5r6WktNrW1VvdJ2+t+x64Zg7xmWs4qSxZs70Xqs3au0lpzd2XOtc24u8bUXPNvb+20TdxrfMBQvd9pboXIcA-Q0Di7cOZsQ-cMlmtwmpBruWwFLLE3zuUsim4dH86iewZS8No7ZWAoVfx69pHaOcOzf6wFBrJWqejdZ-Dyjxbqtc5R3xsng32dY9E49gK7GXuI8JxLj7AUFvQ45zjtHq3Kv05lyruXaP9si7RWLjLAVTtq+l-qsn1bScBVu7r7HsO0fPeN7zhnxO7PM79gFL71v9dk-c1Lx3Gvidg9w0e7KEXFtK7tSHh9vuuP6sj1dkP37Fei5CzihP3OuszrTwL71IfisruTw97Fuf0-rcz+lcn2eGUh7Z-nvXKei-l46w7mPDecqep2-08vwva829T13kvBPY-98rzlEPCvPf17HwP9XQ+crbddyHnXPf9eL+nyb1vbRzcd5D1b5fk-y-27p+vnf8fy8e734XkPPvm9tqvz5vjs0o6h6T3Xwvj-yQRY837-V7+4tXd-+jmHgXulgAXjoDt-tiqAf-lNIahTodsAQ2gAbTuAS3kgdAXNO1nAfdiATAb1pFgjhAQAe3q7gAd3pjq-jgRgdAmvoQbgQmh3gAePhfpQU-qrkfrQVQfPkegAUvuQb3pAbgUbuwagYIegU-rvnwfrgAYfigW2tIWIR-ufpIfXgAdfsIXIbgYHoenxqnOtFDhPoXroREJ-tHm2kYRFvOuYYngYellYTQS3nYSPm0OYXnsoYYQdBXl-g4R4UzkeuYTXm4bYR4U3uoWBv4VduYWQUFggeupEfYWYR4fQa7uYUwYEQ2ikfEWER4VwToR4bwdERQekXkZkdJuYVvskR4RIQUfweYTIQQd4ZdMYS7n4R4UodUfruYWobIVkY0aDvft6kLPocwQ2oMSUTOqMU4ULNYcMeulMWMXunMZMdpK4e0fXkLMgfUW2usVdkLAEasYXrsfMZSocUsXAIwNQRjvselkLJLjfmBjcTsdpKkVcSMU8UcfqkLDkQMdpPkU1jETykLEId0dJoCY8WcbxFUX8YUbMdpHUTzi3kLM0XxkLG0VCfwSie8dihiQLkevzMQM-jYQ2niSYXcdJsSfFriWYPidMWkeusSWAZsWBvSVdsSSsWifrqyZiZyU4cSXseyfXryVyVSXgfOsSVEfyYXmKUKUYBcaKcKc8RKelsSWwcCTOsqSycKb8ZTv8XasSUCYyWSZqRqTKZCdqdCTysSXCRnnupacafiaiWafwcSV0QaWqcKVoZaN6hzLxEMbSTyt6SSaEdJgGRSXxgGTSS8euuGZidGU4QGWyY6frvGTGQQNgBXvOgGXyYmfXpmSmWmcQUegGeKdmYXkWXmbxEkYWambxAqSWelgGSqa6Xug2VdgGVqfAeaXam2eWZvq2dWbZlgT9jigGVaaXs2f2UiV6f2Q6R2fwQGS6fCW2vOf0QylWFADWL6ZGQCVgBuZiWubuUseuYAS-uiTuejl4VsWeRKh3vuRXkAZ2TireRsYufcWeb4ciWeVmbOfrreSEaqQsZ+Y8UecWd+WsWebcUGeMeBUBTWLWaBQcWeY2S+SCYhTBb2ZcYqa8UefqchVBdhWhaafBdcWeaOYPliSRWhTOdgVhTWAudaccWeR6TXN6nyKbPefwaxQwBeWBpxXAPmlIHSIIGGEYrsPDDUO6tQDgDWGygSq7hmPrOxfrvJVmNxdJspW4POqrKiMKkZripJTWGgAUKYWBhklJbuvOuwbpaZdJaCsZWpfpZBEZXeAJdHNwMJacKJS4PMHpWZTJWMuMpMpALAAgMgDkoEHgIEAQKshihssgKoAMscH-OIC4GgEPDAPXNINwGZGgpaCSBlfjLoNZJDClRFXXDMBcMjMvEUlwHlVIBcBALqJFdsFsBAIEFwPFXArsKCBAO1LVZlZRIEIEPIqiLgDYPIl0O1QlV1a4AQAkHoHgCgEcHADcDsH1RcDclkjDCCjaJCuqNwMGAnJqAcBkDstkKEPXN8rWCGHgAchYEcngAYA8rcDlEQMQFwEtdwAALzozzVgI0jwB4AdUwArW4D+goAoAvzLUoA3iPAfXfVdB4B-XXRwD+gRhPAACqVocCisFwFgw8pilwcM6VT4SwpMCINIuwbATsGA8wig3V7US1loS1eAbSKAfcNk-o-o2VFgYNENH84NEYEVJN9A3AoQOY218yLIEK8YgtqIcwi1ZwKqEYMN0Ag1KAXQX1P1Qt5IKA0AtgesGA-o0YCNetKA9ovQxARtt4pkYAAAkq1d6BNN6C5BcGMNdNQPGGQCUrwAjcUDPN6CgNULUAbVbYwowgjUHXACHd7WHT7fNa4C7YHV5TYEbWAKIMnRgHfOQDmLILqDYFLIoBndwPbS7Z7dwCWPIgWAWJXdeF7dbbHSIAjQnQHQ1c1A4Kna3fnZQFnfIvGLnW3ZQMXQ7RcFfDUOSHQGXe+BGHXQ3WHU3cPSgECAwKnUvXAD3TmGMMCEPS7dwB6OlbQHUGXTUr+J9fGKWGGE2G0LfFfVndPTHbHfPYnaIKTETKnc-a0ETOvfGAeK4NbFYC-ZYCXd6GXWAn3HAHffXbPY-QHVgNqNQOgN6PsBAKIKHbPQ3fGLAwYD3ffWg-GClHMAYGDIgzCExG8G1eQDg7PUTNQGPKIJ9cAPGONIENCDwJRGXYw8w3TGDOw2AEwyw7vTw3w1w2MPGAALoz1oNUgQOSNUjQN0AoDawsMIMBC0Cp2KN0xf1gCURQhcMHjEP0xgDSNoNGNQPzXai2CoMyM5h-XDxnCwBuTowow5gSNWMI1sAFDxBQCp2pB3CvVl3iCoiqCn1gCZC7LhAXWtBXW2A3WHLHKPU+MvUPCGMuMyP1RaUjwJNtBLXzBhV4DcCgPtTpStBJwLAU2e2UMMJuNkjxA0C1Cp0g34B+PJMVM23vxYiE1rxRylMgjI14DlOQMN2UDFDLIoDBMOiZXjN0D8aqz9OSMmMN2+3rnkzbW6jIOWMyMI3H0njoDUCnDrNWN7hgAACyjolsg92DAzkj8Y8KszBzVIS1wTFsVsGABAtzVj8zkjmzRg2zGSezLTYd8YJzPoUsPkKTdzZ9Z0YLBzDz8YDstAdYrzFDlzYdHzaDXzv4OzfzyLs9gLpzUsCUULVj8YXkbzdz3T8AwT2cHtSLdzqLjCdLlT81NMNN+zaLTLT4OAKAXIdIqdZk5VTtQQwDzT2LjLeA5MidRVKq8Ykrt9hLDCDLsj7LLL-zcdJyHLXLBoht8YYCitArpdwrdzCN4rAdDA5wKAvwGAes+gMAqdyzprdAsrFTDL8z8zJtPwZt2Al4rLhzo9OA49jERgWILzpLireAftyz1oqzKAEQMM3rorzLOAcbD9SrnL3LKd39+j3AAAarUtgFDDLXK8mw9Qveo7QMo0g943QBAJo27YUhPQawc3Iwozo2W2gPo5WxAKCzmGZJbKSMG9nUM7LKM-GGgFW37L29bAWyq1rc3fI6WxAOW6oyO1WwSzmNYI7Ai2XYOyM8E6O7xHC9TYiwq3PfHSWy2wu22yoxAB202Dw-bTMwO8M6IMO2AHu9M9S8e+Hae4nfO4u9e8uxANYtnfGIoEHCHFu0+y+2+6IGB30E5A2649+wHb+5exWwBwRMB2AFfAnEnBB0O7u2O-HBgInFjFOyK6G7O820o6h0u6+1W6JL3WAJvVHBaI+-hwB4+Cx2R3M4W43Sm0mye2qzTRq+aKnfg3A0Q1e9wKuKcPYzZNx420h-I5g-AzR2s9OzbSp6CxpyICB1TXWPMOJ4Q6QwCCGwcww2ANYFiOe59Dw1Z2iFw12yB5eA5zCAlOI9O5+6K5Ryp3+ygzp4cypwSwFzmPbQTUZ1cCZ+Q7x7PRZ0IzCJo-FzwE57w5w252IzFw3a4KYp9aAyeJl1I5l15wjQmwJ1+0J6m5q6nW6DSFmL89J7J+lfJwhxs0p7MrV24L8ygIbIEGV+g1QB1xc2S7p5Z-pxy7vR1-V1F2Z1YxZ7bQwMcJo-N9dG5XewtxxBl55wV3x8W4nUTJCJ17s919qr1yF-GPt1mNp+RwC3bdMK4EsDVwd1NydzNzIxZzVzQ44NwGw5hx92PNw795IP93VGAB59d4wtl-d7l2A9t7wF58V-x9OyV+q2m1q5Zy51CNvY7b6+PfB15xRwvRCNZ-oPon17HbCxjw6691c+j8T3oPolj-W7DwwhZ-ZzZz94x2z-wweHZ5T1wyD2D7S8z020T2iGTzd6L1CFd8N4c0c6knoA41z4z9T2g3N+twABprcrfPBa-HAABam34PDCMA8vbk0P+XW3TrmXyPyrRvNvlXon2rurQDI9Y9-yCniHu3Jritqd9rmjOr5wyvLXnzbX9rCjct4vjC8Y9rJNUAQ3MvTvgfHCZgQfzPNttbUAqSCwurMVIt6TiI9r2wctsIbvTPlvdvbX9oyyEQAlqdVfz9Almj2V1fAlQf8PmXcIOAFgn1XkmXES-gz7cAPMxAn1iYIycAcrLrKTbrtgHrFtcb8YHoO1r3CNL8xALNz7a-KApsNrFTCN5jkfWtB-RrztAdXQqdXQEtYKBbOM7Hay9AUA93aKogmcwfaD27z7wT1AFrqgacNYmf+wFXnDxjpT9ja81U2ubS9Yx14wEwSgHnQf4sMV+81Nfhvz5paBt+C3Prvvz0AWMkeZjHAYf1DZ9s3A28KYIQJu5phSokjFAAACkMYFwVwEiHXhDwGBogCAO8AuBPJ7AbwUQPIjxpbBC+8cEmJbCdA8A0A7UbAPtUDBHMFqNiA5u6DgT1xegItWAfALYCICa4dzJGlYHpqTxN4ZkAgGTB4DxVgqNfesPIh+CP9ig9SbYBcGAASAZqEVTYK0BOTUBzqBAURv6FCZnUHBPVJwd8lcHuDQg+PPyAMnsC1BbIRNC2HABpDIMcBSwCEJwNUDcB0attKIQfSVh6DL4bbTENqCxhDx6ANgdRr8FhBR1tgg1amLTFoDxB8mxMLpFY1ORKC6gtkVEPkjli9B5gZNbgAACpuhjsaoEIjujbAxoGMXpJiFaAEBehBQzUIzHkSkg3AJTVoNwDMDVBB4WladrUFDDUAKkYKDpnLQYDLwBkqgODnTBlJrlag5Q6yA4CqHIM+mmgg5uNEBgmD4AZgtwGlTcg40BBFNAAAYI17QOtPWiHQjDfD0hygiql8KWBPM+27UPWtBBuGU0+4UISyBP2naBtJgJTdJq4DoBdB9AJQqQAUGwD094R1AZIbnwqqUABkyyTUKb3ab2A4AI0PJquG1iWA6REQJgTwAxSP97hVjGpJbB4EFCd6OwY1hcBc6fC5h2AMkBPAsDaoYI3TbgL8P47Ai4YD-J-rsEEQLc7h07IYAoP3pgjvuq8cUEiNRByCrG3Q7QU+CJimwjRG8ZIY-EuGVD+Gzw+kVIDcDdDlh6VBeHolPAwBJKmgWpA0GGHzBUQowtAOMIaB5MAA0v2GnaNCMhUMUeG4CWAKi8AWzZar81RogidgyY8NgHUjYwAF2MbHJBmNhAujLg49GkJfH2BIh9h9QmRtDCDjYjsow1PoEoOqAlCcx8YiwLoG2BAhmGhNbUKoGOEjULgiyHiLsHp59BNRRvAADxsAbBH-YJnOPaZLiII0MBXulHjAAA+adrOO5bbiZxPofcXc13Gbi96TQ+gNOPOTiAjxBzE8bbSa7I0EBdMS8RYBvFWMTx6NCELvXXgvjrxO418YoHUEYxfxb4mRi+IwCgTJGv42kJBLQazjrKsE2erOIgn-icAm4nNr+DBi7MXxaE1CZuOnG1M4Am49Fj812ao1LxhE-CeclwkHi0JQLM5twDGBghrI65HCYhIbqzi0JPbX0TZzShzACAbEncechQkHiRJx4ugGhLdActBJtE-CZRPt7kTQglEmSeJMknrIRaHoFUb0AwAqTbxEkzcdxMpi8TaQAk6iexNjrgTzJYdZCVZMYScTNxgYJZt6F0nvj9JBEySkRMWb+15GeYgsbGwjAUSPJVE-SXhLPFxiJoJoQkbohuEuSwJ+kwyQ2K4Z8SpKsUqCcJNskMIbJeE2QD8DhEsNUpcEtyfJPmr-DlqgIp8IpOUlmS8J2VckFYB9ANjkRBUpCfFIGRGT+GyU0ySFJnHpShJdABCX1N6RYh9xWokYPeI+F1B4RB4PoBcB7bqNuoJomRlfFiHvCsQONEprGLBG8DNQXItgIwP6FggGAItP+B7GQbTD-al8QiXk0-E9Np23wgAAIjU6QII2oMiF0DzIsh3AYUZPCNjntRo8wVWI0TlFy0dGJQi2A3FgCDh8hPo2oG9SN5dCHpIM3ERKAKTHCoQII9JpHWWGDi0Q8QRaZI1XAohN4C8XAD0GxgSA3gpCO8EsDyprS6gE8bsRkgsByjUhgY3YJ1EHhYhQwNQxMJvFnbTtj6NQG4eNS-GIhvhqIYiMWI0BWh+GVYliMiMRjGAJZXQbKNwFTEtDIRqICEPQGnYtItKms6gCHCThTi7m2o3elIAypb0Dwz1RiF0Fhn3ddqdzVcDjNBlLBkQlsg4Qkx9h2zLwDsrqpTJybBxFBLgCQOzItZGBuAiY9qE8gABWDnX4A4m5EyNLEPQ7oVmzBBkRjAmkgYUdLai9DBAq4PYENLBCWAoAOMMwJdNBTLwHQToRxiUztFHASmAiIRDADuF3Me2zzdqGynBCSAmk1M-JBiA6F1z8h3wj-lBzHZQjJ2YATMWNGqDOInwWE25NkjapG8P+k4-GWgzDB5MzRdcCGf9HaiAS0gHLUQN0MEBHNdpXI5UTnLqB6CRaowuqdrEpG2QvghfUUc0LbkHNTA5oHuQHMcY9M7wXQIpPxkpoEAyZhw7-s0GaQM0fh9vETjyyVGbS6gJsg5h8nlFhS9RgE0BUnG+GCABq1kLudUMOk3y9gWC-IVWNZlvzMhMHImM1QAVXteBMY4+RYLGipjnKpwScSkNFkU0Pq9oLAKwEHj7TFBcYrYC4ETF3SSJaYsiTCzACTz+2wI5BVYybDbzuhjk7yVlUthWgFeNkfOdwF5lAyy5VYGoJBHXjzAOxaolucPLVB3NsxTknyfDCjaFjeuSoroWFQGRPMt6nfZmbwuCoewBBVweWa0IOmDCJ6RvUQPaEoAlMdgRgaCArCQUbzZ6byHoWlDCWEKShbtdoafOLoPicaawWxV8O7FzAckFwNco4A0BaAGaVwAcUOOIUUjwS07L0VsAxglMxZa-IaXABBHeL+Fl8RgaVNBHvz4lDdNKPABgAtJKxC8dajbM6DdA-ZFMvucohKGVUy5To14Z9KCW5z2orFV+Eb1RCkhXAGIrEKcD0A2DGAbwWUVWO1inIYZW9DQI2KWAAhV6-0o6gOOuEsM-F3TVERUJeVcMsRNgI+I4A-lEsUIQKkLiEMYRjzgmnIp-t4mOBAD5WzPcFfGG-6-K-+Okb0NSyK4gCUmrrcAe6zCXawU62KmIO6xtTwx-QTbKuCgBhko0agEK0FJSo8ky15m9QLELu2er3BjAbtH0aS1aX1JzeKI28A8yWp10VaSSApOzLsAp1Z28iYUR4hOG0AIweSR6YwDpARVyq0YZJFVUhgFhUaeSKkN3M1ogAKm8YfWcKnjBwRXwkLI1a+3AJmrtoKYZMLCulYTt+2cEEcAeBCivdtCsdXxN8E8QBBDaQqnMAkxlpszmaCTVwbGgqbdyEggIYEP6DDVsq2UCCeBtqChC+9-qTgQxirW9XJDZ2EaqQPSrqZo1Pq31eMFXDNUVNDKmtbuRZxNVFoxGFTVQNjG+o1qR2Nq0HlGtBTxB7lcaw1WADrWDJbVTaxjuwVtWGUxk2asOh5W+qtUw2rgPFY4H9AV0BR3oGIHnTObarp6n0fFDHXagzrwqmMf0KcDRpui816dZoJnVRox0MQBQCwdOqqp0AWQRySVigz+WQhQUn1VtdaoIJiMuIYdKAKcFVWQwj18iAgPIjZSfqu1FnWRYi1EZ-rGEAGlkI6EWqtAsQqdRQPd2viLw9WQrcDR+q-UDqdUv6mOohsSEQ18VbKf0F+tHWg94NDCRDfoCzAes+FKDbuZBp2q1q1Y9a2jdes3hhLMNjA0jZFEnHqydVFTfjb0CQ3yN0o5ISjQRq42DqeNIrCTRKDI1GB-oXjEsNElbB0aqQqIRscYOgiLSlVo1DAAgkVrqqxVdrRWput1UiB9NlkHgGmEGBgA8AMcmhv+xFYWcNVdjB8RDV+ksMxN2dd4HpsdCOacwiYALVw2+n2t4w7wURiAOM1PSbAc1SzckMv7dyxNAzfVd9WAAJaBmqUOAFcJpgMBQ43gvZOPQ2p3JwqpyUINvCWShA3keYJSfQLgQTilJoKUIEMEDa7plYYdEYIoEfh8JtkWQCrbE1cFnILkVyB5Jkmq0PIZgzyDsGvVUAjhWwqgJsF8lNgdbCh9AOrYbP6BNaWtewNrfog602g8AMAHAAAH4WJrgT6gWCGCBg8wU4VsG0EDBaJZIAzdJmymmEWd9yZdboVVuXlX9RAojOzRD1JFVzGBFnXijw3UpiNwdgzTBK4DthJzY6+qgANS5a8BeAA-iF2wEWM2U4GyDp9VUSBBYMmoNAF+mXjOCWGneYoMjLvA5QQAbKMZBcQ95ktuhDDI3kWwP6qIWdoKNnSAAwB0o2OO7MnRToZQC6bQQukXTLRC5Uh0m3SngDAX9DwpK6FqjXRGhC6C8ZeCKlgFTuC5G9dNYdfLTHQc3EctaYCMkIGEOlYD8BuAo3lzvx0O7yB5XPHTzvf6gpid+HCXXmEp3U6ImdO1EAzviHZ9zgjlNoNLqkCi6FdIgUFYMxJ3nd4YbQS7RTpGWwZYVsdE3VY2+1Q6eA3OmXgwidWdys9uDNOu+sPZl6cWYActTSyL0jd84ZfT3VHzABUtq9-XaheB3r0N6cwRHEjuyB70N6y1GBVjmnxED5a7muuhoUnrAADI2RU8VPbQE2DhLM1RXa3q7unbO6W9R-AgXHtVYH8idt-cXdK3T1U6wwNO75HTHp20wShUu1nRzqL367rQqenKP7oz1G6i9OemRnnoRjQ6R2mYJIJh1h2YdCNuAOHe2sn0HNp9MjfXfPtvlTMfREAFffithUI8w2tilZvmOjaxs+hXan3Tu2NWYIl9yBhdZmudaWguAYVTWngv9BhV1aegWVRKowA3gAqUyYKswGVl6Adl78ugOcGirqS6AzAXwQQGABLV8tBMSVilS4Ct1IqXAcZKIyAA).

```yaml
meta:
  name: 
    short: NHS
    full: National Health Service
  link:
    home: https://www.nhs.uk
    brand: https://www.england.nhs.uk/nhsidentity/identity-guidelines/

# # Download the NHS logos and store them next to _brand.yml
# # You'll have to update this section with the correct file names
# logo:
#   images:
#     header: nhs-logo.svg
#     header-white: nhs-logo-white.svg
#   small: nhs-logo-icon.svg
#   medium: header
#   large: header

color:
  palette:
    # Core neutrals (Level 2)
    white: "#FFFFFF"
    black: "#231F20"
    grey-dark: "#425563"
    grey-mid: "#768692"
    grey-pale: "#E8EDEE"
    
    # Blues (Level 1)
    blue-dark: "#003087"
    blue: "#005EB8"
    blue-bright: "#0072CE"
    blue-light: "#41B6E6"
    blue-aqua: "#00A9CE"
    
    # Greens (Level 3)
    green-dark: "#006747"
    green: "#009639"
    green-light: "#78BE20"
    green-aqua: "#00A499"
    
    # Purples and Pinks
    purple: "#330072"
    pink-dark: "#7C2855"
    pink: "#AE2573"
    
    # Reds
    red-dark: "#8A1538"
    red: "#DA291C"  # Emergency Services Red
    
    # Yellows and Orange
    orange: "#ED8B00"
    yellow-warm: "#FFB81C"
    yellow: "#FAE100"
    yellow-emergency: "#FFE600"  # RAL 1016 Sulphur Yellow
    
    # Bootstrap color aliases - using closest matches without duplication
    indigo: blue-dark
    cyan: blue-aqua
    teal: green-aqua
    
  # Semantic color assignments
  foreground: black
  background: white
  primary: blue
  secondary: grey-dark
  tertiary: grey-pale
  success: green
  danger: red
  warning: yellow-warm
  info: blue-light
  light: grey-pale
  dark: grey-dark

typography:
  fonts:
    # Note: Frutiger is a licensed font you'd have to purchase or download
    # - family: Frutiger W01
    #   source: file
    #   files: 
    #     - path: fonts/FrutigerLTW01-55Roman.ttf
    #     - path: fonts/FrutigerLTW01-65Bold.ttf
    #       weight: bold
          
    - family: Arial
      source: system
  
  base:
    family: "Arial, sans-serif"
    weight: 400
    size: 16px
    line-height: 1.5

  headings:
    family: "Arial, sans-serif"
    weight: 700
    line-height: 1.25
    color: blue

defaults:
  bootstrap:
    defaults:
      # NHS specific variables could be added here
      enable-rounded: false
```
