### ISSUE TITLE
Heads up: Bootswatch theme id supersedes brand_yml options

### ISSUE THREAD

**Issue by morrisLuke** [posit-dev/brand-yml#56]
Love the `brand_yml` tools. Finally getting a chance to play over the weekend, and I was having trouble getting my chosen colors for links, header background and header text.

Turns out a Bootswatch theme I'd previously chosen within my `_quarto.yml` was superseding all the branding work.

```
project:
  type: website
  output-dir: docs
format:
  html:
    lang: en
    theme: yeti

```

Once I noted out the `theme: yeti` line, the branding choices took effect. A heads-up somewhere about the Bootswatch theme taking precedence may be useful to mention in documentation for other normies.

Thank you again for all the work that went into this :)
