### ISSUE TITLE
Add brand font Sass vars

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/brand-yml#58]
Add `$brand-font-{family}` variables and maybe even `.brand-font-{family}` utility classes.

```yaml
typography:
  fonts:
    - family: Quantico
      source: google
    - family: Monda
      source: file
      files:
        - path: Monda.ttf
          weight: 400..700
    - family: Share Tech Mono
      source: bunny
```

Would create

```scss
/*-- scss:defaults --*/
$brand-font-quantico: Quantico
$brand-font-monda: Monda
$brand-font-share-tech-mono: Share Tech Mono

/*-- scss:rules --*/
.brand-font-quantico {
  font-family: $brand-font-quantico;
}

.brand-font-monda {
  font-family: $brand-font-monda;
}

.brand-font-share-tech-mono {
  font-family: $brand-font-share-tech-mono;
}
```
