### ISSUE TITLE
brand not applied to dark mode in Quarto HTML

### ISSUE THREAD

**Issue by Aariq** [posit-dev/brand-yml#68]
I'm not sure if this belongs here or in the Quarto repo, but it appears like using `theme: brand` doesn't work for dark mode, only light mode.  Perhaps this is just not implemented yet, but I was expecting something like this would work:

```
format:
  html:
    theme:
      light: brand
      dark:
        - brand
        - dark.scss
```

where `dark.scss` only overrides background and foreground colors.  However, when I do this, I see that in dark mode the fonts and everything else changes.  Even just using `light: brand` and `dark: brand` makes it clear that `_brand.yml` is only applied to light mode.
