### ISSUE TITLE
Add UPPERCASE as a "style" or "decoration"

### ISSUE THREAD

**Issue by dyavorsky** [posit-dev/brand-yml#75]
My company's brand guidelines uses all uppercase for headings.  

Can this be implemented possibly as something like:

```
typography: 
  headings: 
    style: uppercase
```

**Comment by gadenbuie** [comment]
Thanks for the suggestion! If we implement this, we'd follow CSS's lead and use [text-transform](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform) for the property name. The `text-transform` values we'd likely support would be:

```yaml
text-transform: none
text-transform: capitalize
text-transform: uppercase
text-transform: lowercase
```

Or in Quarto's YAML schema:

```yaml
- id: brand-text-transform
  description: A text transformation for display purposes.
  enum: [none, capitalize, uppercase, lowercase]
  default: none
```

We'd have to look into the broad availability of this type of property. It's certainly available in HTML via CSS[^1]. In other cases, we could certainly use [a Lua filter](https://tex.stackexchange.com/a/593812) for the transformation. But what I like about the CSS approach is that the text is only _visually_ transformed; the conversion isn't permanent. E.g. `<span style="text-transform: uppercase">My Special Content</span>` will display as MY SPECIAL CONTENT but is copied as "My Special Content". (I'm not sure how relevant that is for other output formats.)

It looks like Typst has support for `#uppercase` and `#lowercase` but not `#capitalize`: https://typst.app/docs/reference/text/
